from keyboards.admin_kb import *
from keyboards.back_kb import *
from keyboards.commands_kb import *
from keyboards.menu_kb import *
from keyboards.prime_kb import *
from keyboards.reg_kb import *
from keyboards.settings_kb import *
from keyboards.stats_kb import *
from keyboards.student_kb import *
from keyboards.super_admin_kb import *
from keyboards.teachers_kb import *
from keyboards.url_kb import *
from keyboards.user_kb import *
