from src.keyboards.admin_kb import *
from src.keyboards.back_kb import *
from src.keyboards.menu_kb import *
from src.keyboards.reg_kb import *
from src.keyboards.settings_kb import *
from src.keyboards.stats_kb import *
from src.keyboards.student_kb import *
from src.keyboards.super_admin_kb import *
from src.keyboards.url_kb import *
